data:
  dataset: "Statlog"
  features: 36
  data_dir: "./data/Statlog"
  train_ratio: 0.5
  val_ratio: 0.1
  test_ratio: 0.4

model:
  type: "paper"
  latent_dim: 20

training:
  batch_size: 100
  n_epochs: 500
  validation_freq: 10
  patience: 10

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
  grad_clip: 1.0

validation:
  batch_size: 256

testing:
  batch_size: 256